language: java

jdk:
  - oraclejdk8

install:
  - pushd .
  - mkdir .nemdeps
  - cd .nemdeps
  -
  - git clone https://github.com/NewEconomyMovement/nem.core.git
  - cd nem.core
  - mvn install -DskipTests=true
  -
  - git clone https://github.com/NewEconomyMovement/nem.deploy.git
  - cd nem.deploy
  - mvn install -DskipTests=true
  -
  - popd