language: java

jdk:
  - oraclejdk8

install:
 - wget http://bob.nem.ninja/nem-core__V0.3.7-ALPHA.jar
 - mvn install:install-file -Dfile=nem-core__V0.3.7-ALPHA.jar -DgroupId=org.nem.core -DartifactId=nem-core -Dversion=0.3.7-ALPHA -Dpackaging=jar
