language: java
jdk:
  - oraclejdk8

install:
 - wget http://bob.nem.ninja/nem-core__V0.2.18-ALPHA.jar
 - mvn install:install-file -Dfile=nem-core__V0.2.18-ALPHA.jar -DgroupId=org.nem.core -DartifactId=nem-core -Dversion=0.2.18-ALPHA -Dpackaging=jar