language: java

jdk:
  - oraclejdk8

install:
 - wget http://bob.nem.ninja/nem-core-0.6.28-BETA.jar
 - mvn install:install-file -Dfile=nem-core-0.6.28-BETA.jar -DgroupId=org.nem.core -DartifactId=nem-core -Dversion=0.6.28-BETA -Dpackaging=jar
