language: java

jdk:
  - oraclejdk8

install:
 - wget http://bob.nem.ninja/nem-core__V0.5.16-BETA.jar
 - mvn install:install-file -Dfile=nem-core__V0.5.16-BETA.jar -DgroupId=org.nem.core -DartifactId=nem-core -Dversion=0.5.16-BETA -Dpackaging=jar
